feat: added experimentation client project package
GoogleCloudPlatform/pubsec-declarative-toolkit pull request #381
Opened 2023-05-31 18:20 UTC by seanwilkens-ssc

new package for issue #370
(additional PRs will be created for other packages and to update documentation)

**`solutions/experimentation/client-project`**
- includes / deprecates packages:
    - solutions/project/project-experimentation
- depends on:
    - solutions/experimentation/client-landing-zone

2023-06-01 12:04 UTC, davelanglois-ssc requested changes

2023-06-01 12:04 UTC, davelanglois-ssc commented on solutions/experimentation/client-project/network/subnet.yaml
> +  secondaryIpRange:
based on the latest discussion and documentation, kubernetes cluster will be deployed in their own subnet.. so we can remove the secondaryIprange section for this subnet

2023-06-01 12:04 UTC, davelanglois-ssc commented on solutions/experimentation/client-project/network/subnet.yaml
> +  secondaryIpRange:
based on the latest discussion and documentation, kubernetes cluster will be deployed in their own subnet.. so we can remove the secondaryIprange section for this subnet

2023-06-01 12:04 UTC, davelanglois-ssc commented on solutions/experimentation/client-project/setters.yaml
> +  # Naming Convention for project-id : <client-code><environment-code>m<data-classification>-<project-owner>-<user defined string>
we could remove this line as it is the standard we adopted for all other packages

2023-06-01 12:04 UTC, davelanglois-ssc commented on solutions/experimentation/client-project/setters.yaml
> +  ##########################
based on the latest discussion and documentation, kubernetes cluster will be deployed in their own subnet.. so we can remove these gke setters

2023-06-01 17:23 UTC, cartyc reviewed
Looks good, will approve once the changes Dave requested are pushed.

2023-06-01 18:14 UTC, cartyc approved these changes

2023-06-02 03:02 UTC, fmichaelobrien approved these changes
LGTM 
Pending requested changes

2023-06-02 12:45 UTC, davelanglois-ssc commented on solutions/experimentation/client-project/README.md
you will need to regenerate the README

2023-06-02 14:05 UTC, cartyc approved these changes

2023-06-02 14:06 UTC, merged