Adjust Gatekeeper Policy Installation For Improved CLI Installations
GoogleCloudPlatform/pubsec-declarative-toolkit pull request #414
Opened 2023-06-26 12:39 UTC by cartyc

This PR moves the gatekeeper `constraints` from the `gatekeeper-policies` package to the `core-landing-zone` package. This will help resolve issue #409 and allow for easier non-gitops based installation approaches as this allows for the `ConstraintTemplate` to be installed before the gatekeeper `constraint` file and prevents the issue where one would need to comment out of the `constraint` file first before apply the `gatekeeper-policies` package.

The overall goal of this PR is to improve the installation process for users of non-gitops based installs, `kpt` in particular. This would also allow us to install more `constraintTemplates` via the `gatekeeper-policies` package into the cluster without needing to enable them right away.

2023-06-26 12:55 UTC, fmichaelobrien approved these changes
LGTM
- nice, thanks for the constraints move - Chris

2023-07-06 12:44 UTC, cartyc commented
@alaincormier-ssc @davelanglois-ssc @fmichaelobrien I made the changes discussed yesterday and wanted to get your input before I start fixing the README and Kptfiles.

Created a new solution directory called `policy-constraint-bundles` with 2 bundles, `guardrails-v1` and `naming-policies`.

2023-07-10 12:00 UTC, alaincormier-ssc commented
> @alaincormier-ssc @davelanglois-ssc @fmichaelobrien I made the changes discussed yesterday and wanted to get your input before I start fixing the README and Kptfiles.
> 
> Created a new solution directory called `policy-constraint-bundles` with 2 bundles, `guardrails-v1` and `naming-policies`.

that should work
will each bundle be tagged by release-please?

2023-07-10 12:23 UTC, cartyc commented
That's what I was thinking, might be overkill but I believe having specific task based bundles makes sense. I was using the Anthos [Gatekeeper Bundles](https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles) as by point of reference.

2023-07-12 00:38 UTC, davelanglois-ssc commented
Hey @cartyc, I really like the concept. If I understand correctly, the constrainttemplate would remain in the existing `gatekeeper-policies` package. Do you think that name still make sense ?

2023-07-12 12:11 UTC, cartyc commented
> Hey @cartyc, I really like the concept. If I understand correctly, the constrainttemplate would remain in the existing `gatekeeper-policies` package. Do you think that name still make sense ?

That's correct, the package would just act as a means to load the `constrainttemplates` into the Config Controller or GKE instances, similar to what happens when you you enable the installation of the default template library on policy controller I think the name `gatekeeper-policies` still works but maybe the bundle names might need some additional tuning to help keep things more distinct. `gatekeeper-policy-templates` might be a good option though if we want to rename the package.

2023-08-09 12:51 UTC, fmichaelobrien submitted a review, later dismissed
LGTM
- nice
- dryrun is appreciated - in particular for the cost-center/centre ones
- will reapprove if required after lint commit

2023-08-09 12:54 UTC, cartyc commented
Thanks Mike, I was just cracking open an editor to start hacking away at the linting issues.

2023-08-09 14:54 UTC, fmichaelobrien submitted a review, later dismissed
LGTM

2023-08-09 14:57 UTC, fmichaelobrien submitted a review, later dismissed
LGTM
reviewed
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/commit/c62264b1890434f1b1668d1c997834919f62863f#diff-0e4828475a445061adf098b63da0946c315796e05bb5354d1b142e2ec8b6d427

2023-08-09 17:18 UTC, fmichaelobrien submitted a review, later dismissed
LGTM

2023-08-09 20:00 UTC, fmichaelobrien approved these changes
LGTM
- yes lint is soooo particular on CR/LF spaces...
- thanks for taking the heat

2023-08-30 21:00 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/guardrails-v1/Kptfile
I suggest renaming this folder from policy-constraint-bundles to gatekeeper-policy-constraint-bundles

2023-08-30 21:04 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/guardrails-v1/README.md
> +`kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/policy-constraint-bundles/guardrails-v1 guardrails-v1`
you would need to update this link if you decide to change the folder name

2023-08-31 11:15 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-protectedb-policies/README.md
> +All Projects must have be labeled with a cost center code that matches the following pattern `^[a-zA-Z]+$`
All projects must be labeled with a cloud business requirements ID that is represented with 4 digits

Below is the guidance. All cloud service provider environment should be using this standard tag:​

           TagName = ssc_cbrid ​

           Value = 4digit CBR ID

2023-08-31 11:17 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-protectedb-policies/README.md
> +`kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/policy-constraint-bundles/std-protectedb-policies protectb-policies`
update this link if you change the  folder name under solutions/

2023-08-31 11:18 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-protectedb-policies/README.md
> +All Projects must have be labeled with a cost center code that matches the following pattern `^[a-zA-Z]+$`
this requirement is mandatory to all environements including profile 1, 2, 3, 4, 5, 6

2023-08-31 11:21 UTC, davelanglois-ssc requested changes

2023-08-31 11:21 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-protectedb-policies/required-labels/cost-center.yaml
> +    message: "All namespaces must have an `cost-center` label"
to be adjusted as per comment on README.md

2023-08-31 11:21 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-unclass-policies/README.md
> +All Projects must have be labeled with a cost center code that matches the following pattern `^[a-zA-Z]+$`
to be adjusted as per comment on std-protectedb-policies/README.md

2023-08-31 11:21 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-unclass-policies/README.md
> +kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/policy-constraint-bundles/std-protectedb-policies unclass-policies
update this url as per folder name under solutions/

2023-08-31 11:21 UTC, davelanglois-ssc commented on solutions/policy-constraint-bundles/std-unclass-policies/required-labels/cost-center.yaml
> +    message: "All namespaces must have an `cost-center` label"
to be adjusted as per comment on std-protectedb-policies/README.md

2023-08-31 13:07 UTC, cartyc commented on solutions/policy-constraint-bundles/guardrails-v1/Kptfile
Renamed, like the added clarity. Update the links in the constraint packages as well

2023-08-31 13:07 UTC, cartyc commented
@davelanglois-ssc should be good for a final review.

2023-08-31 13:40 UTC, fmichaelobrien submitted a review, later dismissed
LGTM
the dryrun is appreciated

2023-09-04 17:47 UTC, davelanglois-ssc commented on solutions/gatekeeper-policy-constraint-bundles/std-unclass-policies/required-labels/cost-center.yaml
> +  name: must-have-cost-center
should be renamed to must-have-cbrid

2023-09-04 17:48 UTC, davelanglois-ssc commented on solutions/gatekeeper-policy-constraint-bundles/guardrails-v1/required-labels/cost-center.yaml
> +    message: "All Projects must have an `ssc_cbrid` label with a 4digit CBR ID"
minor, missing space between 4 and digit

2023-09-07 13:09 UTC, fmichaelobrien submitted a review, later dismissed
LGTM
- last change good

2023-09-13 13:01 UTC, cartyc commented on solutions/gatekeeper-policy-constraint-bundles/std-unclass-policies/required-labels/cost-center.yaml
> +  name: must-have-cost-center
Updated constraint name, thanks Dave!

2023-09-14 12:16 UTC, davelanglois-ssc approved these changes

2023-09-17 16:12 UTC, fmichaelobrien approved these changes
LGTM

2024-03-02 05:20 UTC, obriensystems commented
closing - keep reference code only

2024-03-02 05:20 UTC, closed without merging