#457 - add back kpt deploy instructions for clz
GoogleCloudPlatform/pubsec-declarative-toolkit pull request #458
Opened 2023-08-15 01:30 UTC by fmichaelobrien

gatekeeper optional - just instructions for core-landing-zone

Test results of all script additions in #457

2023-08-15 01:37 UTC, fmichaelobrien commented
fixing linting

```
2023-08-15 01:31:48 [INFO]   Successfully found:[GITHUB_REPO], value:[pubsec-declarative-toolkit]
2023-08-15 01:31:48 [ERROR]   Failed to get [GITHUB_TOKEN]!
2023-08-15 01:31:48 [ERROR]   []
2023-08-15 01:31:48 [ERROR]   Please set a [GITHUB_TOKEN] from the main workflow environment to take advantage of multiple status reports!

2023-08-15 01:31:53 [INFO]   File:[/github/workspace/docs/landing-zone-v2/README.md]
2023-08-15 01:31:53 [ERROR]   Found errors in [markdownlint] linter!
2023-08-15 01:31:53 [ERROR]   Error code: 1. Command output:
------
/github/workspace/docs/landing-zone-v2/README.md:3[81](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/actions/runs/5862548542/job/15894515244?pr=458#step:6:82) MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
/github/workspace/docs/landing-zone-v2/README.md:3[87](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/actions/runs/5862548542/job/15894515244?pr=458#step:6:88) MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
/github/workspace/docs/landing-zone-v2/README.md:3[93](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/actions/runs/5862548542/job/15894515244?pr=458#step:6:94) MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
/github/workspace/docs/landing-zone-v2/README.md:399 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
/github/workspace/docs/landing-zone-v2/README.md:405 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
------
```

2023-08-15 13:35 UTC, obriensystems commented
I'll fix the linting later today after meets - linting takes longer that the actual PR sometimes

2023-08-18 01:44 UTC, fmichaelobrien commented
ready for review/merge

2023-08-18 12:17 UTC, cartyc requested changes
Looks good aside from the one nit

2023-08-18 12:17 UTC, cartyc commented on docs/landing-zone-v2/README.md
> +Optional
Could we add something along the lines of strongly recommended or required for Prod?

2023-08-18 15:06 UTC, cartyc approved these changes

2023-08-18 16:25 UTC, fmichaelobrien commented
merge this one before https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/pull/476

2023-08-18 16:37 UTC, alaincormier-ssc approved these changes
lgtm

2023-08-18 16:42 UTC, fmichaelobrien commented
Merging and will rebase with https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/pull/476

2023-08-18 16:43 UTC, merged