feat: gke-defaults package
GoogleCloudPlatform/pubsec-declarative-toolkit pull request #480
Opened 2023-08-18 21:05 UTC by davelanglois-ssc

Landing zone v2 subpackage.
Depends on package `gke-setup`.
Requires project-id-tier3 namespace.

Deploy this package once per service project.

A package to deploy common GKE resources. 
- include roles granted to a user or group for visualizing GKE.
- ip reservation for an external global load balancers
- ssl certificate (requires the alpha CRD for now)
- dns record

This package is part of the solution for #479

2023-08-18 21:29 UTC, fmichaelobrien reviewed
Reviewing over the next 48h - I will also test this overlay package on one of my lzs

2023-08-21 12:08 UTC, fmichaelobrien submitted a review, later dismissed
LGTM

2023-08-21 12:10 UTC, alaincormier-ssc submitted a review, later dismissed

2023-08-21 12:17 UTC, cartyc requested changes

2023-08-21 13:50 UTC, lucstjean-ssc approved these changes
/lgtm

2023-08-21 14:49 UTC, davelanglois-ssc commented on solutions/gke/configconnector/gke-defaults/README.md
> +## Sub-packages
added with latest commit

2023-08-21 14:50 UTC, davelanglois-ssc commented on solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/ssl.yaml
> +apiVersion: compute.cnrm.cloud.google.com/v1alpha1
added with latest commit. please resolve if satified

2023-08-21 14:50 UTC, cartyc approved these changes

2023-08-21 14:50 UTC, cartyc commented on solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/ssl.yaml
> +apiVersion: compute.cnrm.cloud.google.com/v1alpha1
Looks great! Thanks Dave :)

2023-08-21 16:19 UTC, merged